folder('Deployments1'){
  displayName('Deployments1')
  description('testDeployment1')
}
folder('Deployments2'){
  displayName('Deployments2')
  description('testDeployment2')
}
folder('Deployments3'){
  displayName('Deployments3')
  description('testDeployment3')
}
folder('Deployments4'){
  displayName('Deployments4')
  description('testDeployment4')
}
